### ISSUE TITLE
irepl-check: IndexError

### ISSUE THREAD

**Issue by dbenaben** [mesocentre-mcia/mcia-irods-utils#36]
irepl-check on a collection containing a file with 9 replicas generate an "IndexError":
```
$ irepl-check -r -u tata --grace-period=7 -M --large=50000 -c /MCIA/home/tata/test/test_bis replFactor+3 --repair
/MCIA/home/tata/test/test_bis/lprussel.tar.gz : 9 (!=3)
/MCIA/home/tata/test/test_bis/lprussel.tar.gz : remove replica #0 (siterg-ism)
/MCIA/home/tata/test/test_bis/lprussel.tar.gz : remove replica #3 (siterg-cbib)
/MCIA/home/tata/test/test_bis/lprussel.tar.gz : remove replica #1 (siterg-ubx)
Traceback (most recent call last):
  File "/opt/irods/.local/bin/irepl-check", line 638, in <module>
    grace_date, ignore_regexps )
  File "/opt/irods/.local/bin/irepl-check", line 418, in do_irepl_check
    admin = admin )
  File "/opt/irods/.local/bin/irepl-check", line 91, in repair_replicas_number
    rg_index = file_rescs.index(remove_rescs[i])
IndexError: list index out of range
```
But, this is not blocking (we can simply redo the command).

**Comment by dbenaben** [comment]
Hmmmm... Maybe the error is due to a resource down during the irepl-check.

**Comment by pigay** [comment]
Thanks for reporting this.
Anyway, we could detect this event correctly and issue a comprehensive error message...
